---

base_locale: en
locales: [en]

ignore_unused:
  - decidim.admin.menu.superspaces
  - decidim.superspaces.admin_log.*
  - decidim.superspaces.participatory_spaces.show.part_of
  - decidim.superspaces.content_blocks.*
  - decidim.superspaces.pages.home.highlighted_superspaces*

ignore_missing:
  - decidim.participatory_processes.scopes.global
