---

base_locale: en
locales: [en]

ignore_unused:
  - decidim.admin.menu.superspaces
  - decidim.superspaces.admin_log.*
  - decidim.superspaces.participatory_spaces.show.part_of

ignore_missing:
  - decidim.participatory_processes.scopes.global
